### ISSUE TITLE
Login error and dosen't accept cookies

### ISSUE THREAD

**Issue by c0bra9** [Estayparadox/InstaBot#10]
Error:

Warning (from warnings module):
  File "C:\Users\strys\OneDrive\Desktop\Insta-Bot-master\start.py", line 22
    webdriver = webdriver.Chrome(executable_path=chromedriver_path)
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
Traceback (most recent call last):
  File "C:\Users\strys\OneDrive\Desktop\Insta-Bot-master\start.py", line 27, in <module>
    username = webdriver.find_element_by_name('username')
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by OSintt** [comment]
change `webdriver.find_element_by_name()` to `webdriver.find_element('name', 'username')`

**Comment by neeramrutia** [comment]
TRY THIS:
def login(self):
        self.driver.get("https://www.instagram.com/accounts/login/")
        time.sleep(5)

        username = self.driver.find_element(By.NAME, "username")
        password = self.driver.find_element(By.NAME, "password")

        username.click()
        username.send_keys(self.USERNAME)
        time.sleep(1)

        password.click()
        password.send_keys(self.PASSWORD)
        time.sleep(1)

        password.send_keys(Keys.ENTER)
        time.sleep(5)
