### ISSUE TITLE
Chrome dirver

### ISSUE THREAD

**Issue by lify97300** [Estayparadox/InstaBot#13]
it says

Message: 'chrome driver' executable needs to be in PATH.

Can I have some help pls

**Comment by DestroFac** [comment]
You have to define where your chromedriver_path is located in start.py

**Comment by Estayparadox** [comment]
Should be fixed with [this commit](https://github.com/Estayparadox/Insta-Bot/commit/47318b08adbf50d803aed77c9391ec6e923044f6)
