### ISSUE TITLE
noob needs help

### ISSUE THREAD

**Issue by luda213** [Estayparadox/InstaBot#15]
hi guys its been very annoying and i need help please
![obrázek_2023-08-29_105337377](https://github.com/Estayparadox/Insta-Bot/assets/95498104/688e2804-867e-4836-8926-97031b216f15)

ModuleNotFoundError: No module named 'pandas'

**Comment by Estayparadox** [comment]
@luda213 by running `pip3 install -r src/requirements.txt ` at the root of your project, it should install all the modules listed in the `requirements.txt` file.

**Comment by Estayparadox** [comment]
@luda213 you can also comment the two following lines if you really cannot install the panda module.
```python
updated_user_df = pd.DataFrame(prev_user_list)
updated_user_df.to_csv('{}_users_followed_list.csv'.format(strftime("%Y%m%d-%H%M%S")))
```
