### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div/div[3]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/button[1]"}

### ISSUE THREAD

**Issue by TuanTool** [Estayparadox/InstaBot#17]
Traceback (most recent call last):
  File "D:\Instagram_Bot\Insta-Bot-master\src\start.py", line 36, in <module>
    button_login = webdriver.find_element(By.XPATH, '/html/body/div[2]/div/div/div[3]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/button[1]')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div/div[3]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/button[1]"}
  (Session info: chrome=119.0.6045.160); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF7CAD682B2+55298]
        (No symbol) [0x00007FF7CACD5E02]
        (No symbol) [0x00007FF7CAB905AB]
        (No symbol) [0x00007FF7CABD175C]
        (No symbol) [0x00007FF7CABD18DC]
        (No symbol) [0x00007FF7CAC0CBC7]
        (No symbol) [0x00007FF7CABF20EF]
        (No symbol) [0x00007FF7CAC0AAA4]
        (No symbol) [0x00007FF7CABF1E83]
        (No symbol) [0x00007FF7CABC670A]
        (No symbol) [0x00007FF7CABC7964]
        GetHandleVerifier [0x00007FF7CB0E0AAB+3694587]
        GetHandleVerifier [0x00007FF7CB13728E+4048862]
        GetHandleVerifier [0x00007FF7CB12F173+4015811]
        GetHandleVerifier [0x00007FF7CAE047D6+695590]
        (No symbol) [0x00007FF7CACE0CE8]
        (No symbol) [0x00007FF7CACDCF34]
        (No symbol) [0x00007FF7CACDD062]
        (No symbol) [0x00007FF7CACCD3A3]
        BaseThreadInitThunk [0x00007FFC12817344+20]
        RtlUserThreadStart [0x00007FFC12E026B1+33]

**Comment by Estayparadox** [comment]
@TuanTool This issue is due to the fact that the paths to Instagram front-end elements are often updated. So you should therefore update the following paths.

**Comment by Estayparadox** [comment]
Duplicated topic https://github.com/Estayparadox/Insta-Bot/issues/16
