### ISSUE TITLE
Chrome Driver Problem

### ISSUE THREAD

**Issue by mahdish45** [Estayparadox/InstaBot#8]
Im install this Program but when im start,i have problem

![12](https://user-images.githubusercontent.com/52581671/133737464-a9ab0266-7734-4250-b10a-2b3160ec38e0.png)
m

**Comment by Estayparadox** [comment]
Should be fixed with [this commit](https://github.com/Estayparadox/Insta-Bot/commit/47318b08adbf50d803aed77c9391ec6e923044f6).
